### ISSUE TITLE
fvm install 1.9.1 解压报错

### ISSUE THREAD

**Issue by androidHQJ** [xinfeng-tech/fvm#2]
error [/var/folders/rw/h6lcy3wj4g17_nl6s19dgbwm0000gn/T/fvm/flutter.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)

请问是什么原因呢？

**Comment by dashixiong91** [comment]
什么环境？
看错误提示确实是解压失败了，你可以尝试一下删掉缓存目录${TMPDIR}fvm重试一下

**Comment by Creolophus** [comment]
1.9.1报错+1，看来不是个例

**Comment by androidHQJ** [comment]
@dashixiong91 运行环境是 mac os

**Comment by dashixiong91** [comment]
@Creolophus 能否尝试cd到缓存目录，然后用系统自带的解压工具试试，如果还是失败，则说明下载的文件有问题

**Comment by Creolophus** [comment]
试过的，解压失败，应该是下载的文件有问题
