### ISSUE TITLE
关于fvm每个SDK版本的hosted缓存的建议

### ISSUE THREAD

**Issue by Notzuonotdied** [xinfeng-tech/fvm#3]
我现在设备上使用的都是fvm，我发现一个问题，就是不同版本之间的hosted(.fvm/versions/1.12.13+hotfix.5-master/.pub-cache)并不是共用的，意味着会缓存多份，这个是否可以优化下呢？

**Comment by dashixiong91** [comment]
可以把所有版本的里的.pub-cache目录删掉，然后设置以下环境变量，这样就能共享了
```shell
export PUB_CACHE="$HOME/.pub-cache"
```
Flutter SDK内部逻辑会去判断$PUB_CACHE环境变量和$FLUTTER_ROOT/.pub-cache，如果后者存在会优先缓存在这里边，如果后者不存在而前者存在，那就会缓存在$PUB_CACHE里
