### ISSUE TITLE
$home 是哪个目录？我之前安装了flutter，但是检查不出来。

### ISSUE THREAD

**Issue by yuexunshi** [xinfeng-tech/fvm#5]
$ fvm list

`current => unset
installed versions:
ls: /Users/asi/.fvm/versions: No such file or directory`

这是我的环境
#flutter
export PATH=/Users/asi/Library/flutter/bin:$PATH
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

#fvm
export FVM_DIR="$HOME/.fvm"
source "/usr/local/opt/fvm/init.sh"

**Comment by dashixiong91** [comment]
fvm不提供检测之前安装的flutter的能力，可以考虑将之前的版本删掉，然后始终通过fvm安装
