### ISSUE TITLE
Warning, but flutter worked well

### ISSUE THREAD

**Issue by virskor** [xinfeng-tech/fvm#6]
Warning! This package referenced a Flutter repository via the .packages file that is no longer available. The repository from which the
'flutter' tool is currently executing will be used instead.
  running Flutter tool: /Users/virs/.fvm/versions/1.17.0-stable
  previous reference  : /Users/virs/flutter
This can happen if you deleted or moved your copy of the Flutter repository, or if it was on a volume that is no longer mounted or has been
mounted at a different location. Please check your system path to verify that you are running the expected version (run 'flutter --version' to
see which flutter is on your path).

**Comment by dashixiong91** [comment]
切换flutter版本时，是会出现这种警告的，这是由于使用之前的flutter初始化项目时的临时文件里记录了flutter的绝对路径，而flutter tools检测出来了，可以执行```git clean -fdx && flutter pub get```解决
