### ISSUE TITLE
安装Flutter却找不到该文件目录

### ISSUE THREAD

**Issue by Dukro** [xinfeng-tech/fvm#9]
**StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm list**
current => unset
installed versions:
ls: /Users/stylookdukro/.fvm/versions: No such file or directory
**StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm list-remote all
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm install 1.17.5-stable**
flutter 1.17.5-stable is downloading...
################################################################################################################################################ 100.0%
mv: rename /var/folders/b3/1n55vz4s4tn13xq6pmhgs6r80000gn/T/fvm/flutter to /Users/stylookdukro/.fvm/versions/1.17.5-stable: No such file or directory
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm use 1.17.5
ls: /Users/stylookdukro/.fvm/versions: No such file or directory
Error: version:1.17.5 has not installed!!
**StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm use flutter 1.17.5**
ls: /Users/stylookdukro/.fvm/versions: No such file or directory
Error: version:flutter has not installed!!
**StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm list**
current => unset
installed versions:
ls: /Users/stylookdukro/.fvm/versions: No such file or directory
**StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm list-remote all
StyLookDukrodeMacBook-Pro:~ stylookdukro$**

**Comment by beilly** [comment]
可能创建文件夹失败了，手动创建就好了。执行如下命令：
```
mkdir ~/.fvm/versions
mkdir ~/.fvm/current
```

**Comment by Dukro** [comment]
> 可能创建文件夹失败了，手动创建就好了。执行如下命令：
> 
> ```
> mkdir ~/.fvm/versions
> mkdir ~/.fvm/current
> ```

额.....并不想手动创建。希望你能修复该BUG

**Comment by dashixiong91** [comment]
source "/usr/local/opt/fvm/init.sh"
